services:
  backend:
    image: ghcr.io/nbesoro/nbesoro-backend:latest
    container_name: nbesoro-backend
    restart: unless-stopped
    expose:
      - "8201"
    environment:
      - VIRTUAL_HOST=api.nbesoro.com
      - LETSENCRYPT_HOST=api.nbesoro.com
      - LETSENCRYPT_EMAIL=bonjour@nbesoro.com
      - VIRTUAL_PORT=8201
    env_file:
      - ./.env
    networks:
      - net

  frontend:
    image: ghcr.io/nbesoro/nbesoro-frontend:latest
    container_name: nbesoro-frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=nbesoro.com
      - LETSENCRYPT_HOST=nbesoro.com
      - LETSENCRYPT_EMAIL=bonjour@nbesoro.com
      - VIRTUAL_PORT=3000
    networks:
      - net

networks:
  net:
    external: true
